"""The chat's shared operation log.

Every change to the chat workspace is an operation. This module gives each one
a place in a single total order and keeps it; clients fold the log with one
reducer (`master-frontend/vd/src/lib/chat-ops.ts`), so the server holds no
chat logic of its own beyond the structural checks below. That is deliberate:
the rules for what a reaction or a membership change *means* live in one
place, in TypeScript, shared by the console and the phone app.

The log starts from a base state — the console's demo workspace, compiled to
`chat_seed.json` — and the whitelist of operations comes from
`chat_protocol.json`. Both are generated by `tools/export-chat-seed.mjs`.
"""

from __future__ import annotations

import json
import sqlite3
import threading
import time
from pathlib import Path
from typing import Any

# Keys whose values are epoch-millisecond times in the seed. They are shifted
# together on first start so the demo reads as recent.
_TIME_KEYS = {
    "timestamp",
    "createdAt",
    "editedAt",
    "pinnedAt",
    "deletedAt",
    "expiresAt",
    "startAt",
    "endAt",
    "scheduledFor",
    "updatedAt",
}


class OpRejected(Exception):
    """An operation the log will not accept. `status` is the HTTP status."""

    def __init__(self, message: str, status: int = 400):
        super().__init__(message)
        self.status = status


def _now_ms() -> int:
    return int(time.time() * 1000)


def _shift_times(value: Any, delta: int) -> Any:
    if isinstance(value, dict):
        return {
            key: (item + delta)
            if key in _TIME_KEYS and isinstance(item, int) and not isinstance(item, bool)
            else _shift_times(item, delta)
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [_shift_times(item, delta) for item in value]
    return value


class ChatLog:
    """The log, its base state, and what is needed to validate an operation."""

    def __init__(self, db_path: Path, seed_path: Path, protocol_path: Path):
        protocol = json.loads(protocol_path.read_text(encoding="utf-8"))
        self.op_types: set[str] = set(protocol["opTypes"])
        self.private_op_types: set[str] = set(protocol["privateOpTypes"])
        self.room_scoped_op_types: set[str] = set(protocol["roomScopedOpTypes"])

        # FastAPI runs plain `def` handlers on a thread pool. One connection
        # shared under a lock keeps sequence assignment and the idempotency
        # check a single atomic step.
        self._lock = threading.Lock()
        self._db = sqlite3.connect(str(db_path), check_same_thread=False)
        self._db.execute("PRAGMA journal_mode=WAL")
        self._db.executescript(
            """
            CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
            CREATE TABLE IF NOT EXISTS ops (
                seq        INTEGER PRIMARY KEY AUTOINCREMENT,
                op_id      TEXT NOT NULL UNIQUE,
                actor      TEXT NOT NULL,
                private_to TEXT,
                ts         INTEGER NOT NULL,
                body       TEXT NOT NULL
            );
            """
        )

        row = self._db.execute("SELECT value FROM meta WHERE key = 'base'").fetchone()
        if row is None:
            seed = json.loads(seed_path.read_text(encoding="utf-8"))
            base = _shift_times(
                {key: seed[key] for key in ("users", "groups", "rooms", "messages")},
                _now_ms() - int(seed["exportedAt"]),
            )
            with self._db:
                self._db.execute(
                    "INSERT INTO meta (key, value) VALUES ('base', ?)", (json.dumps(base),)
                )
        else:
            base = json.loads(row[0])
        self._base = base

        self.users: set[str] = {user["id"] for user in base["users"]}
        self.rooms: set[str] = {room["id"] for room in base["rooms"]}
        for (body,) in self._db.execute("SELECT body FROM ops"):
            op = json.loads(body)
            if op.get("type") == "room.create":
                self.rooms.add(op["roomId"])

    # ------------------------------------------------------------------ reads

    @property
    def base(self) -> dict:
        return self._base

    def head(self) -> int:
        row = self._db.execute("SELECT COALESCE(MAX(seq), 0) FROM ops").fetchone()
        return int(row[0])

    def read(self, since: int, user: str) -> list[dict]:
        """Every op after `since` that `user` may see, in order."""
        rows = self._db.execute(
            "SELECT seq, op_id, actor, private_to, ts, body FROM ops "
            "WHERE seq > ? AND (private_to IS NULL OR private_to = ?) ORDER BY seq",
            (since, user),
        ).fetchall()
        return [self._row(row) for row in rows]

    @staticmethod
    def _row(row: tuple) -> dict:
        seq, op_id, actor, private_to, ts, body = row
        return {
            "seq": seq,
            "opId": op_id,
            "actor": actor,
            "privateTo": private_to,
            "ts": ts,
            "op": json.loads(body),
        }

    @staticmethod
    def visible_to(entry: dict, user: str) -> bool:
        return entry["privateTo"] is None or entry["privateTo"] == user

    # ----------------------------------------------------------------- writes

    def append(self, op_id: str, actor: str, op: dict) -> tuple[dict, bool]:
        """Append `op`. Returns the stored entry and whether it was a replay.

        Idempotent on `op_id`: a client retrying after an ambiguous failure
        gets the original entry back rather than a second copy.
        """
        if not isinstance(op_id, str) or not op_id:
            raise OpRejected("opId is required")
        if not isinstance(op, dict):
            raise OpRejected("op must be an object")

        with self._lock:
            existing = self._db.execute(
                "SELECT seq, op_id, actor, private_to, ts, body FROM ops WHERE op_id = ?",
                (op_id,),
            ).fetchone()
            if existing is not None:
                return self._row(existing), True

            kind = op.get("type")
            if kind not in self.op_types:
                raise OpRejected(f"Unknown operation: {kind!r}")
            if actor not in self.users:
                raise OpRejected(f"Unknown person: {actor!r}", status=403)

            room_id = op.get("roomId")
            if kind in self.room_scoped_op_types and room_id not in self.rooms:
                raise OpRejected(f"No such conversation: {room_id!r}")
            if kind == "room.create":
                if not isinstance(room_id, str) or not room_id:
                    raise OpRejected("room.create needs a roomId")
                if room_id in self.rooms:
                    raise OpRejected(f"Conversation {room_id!r} already exists", status=409)

            private_to = actor if kind in self.private_op_types else None
            ts = _now_ms()
            with self._db:
                cursor = self._db.execute(
                    "INSERT INTO ops (op_id, actor, private_to, ts, body) VALUES (?, ?, ?, ?, ?)",
                    (op_id, actor, private_to, ts, json.dumps(op)),
                )
            if kind == "room.create":
                self.rooms.add(room_id)
            entry = {
                "seq": cursor.lastrowid,
                "opId": op_id,
                "actor": actor,
                "privateTo": private_to,
                "ts": ts,
                "op": op,
            }
            return entry, False

    def close(self) -> None:
        self._db.close()
