import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import type { LocalFile } from './core';
import { describeBackend, extract, sampleExtraction } from './extraction';

/*
 * The expected objects below are what backend/app/extraction.py returns for the
 * same inputs (generated by running it with a stub config), so these tests hold
 * the port to the backend field for field.
 */

const settings = vi.hoisted(() => ({ key: 'sk-test' }));

vi.mock('./config', () => ({
  get OPENAI_API_KEY() {
    return settings.key;
  },
  OPENAI_BASE_URL: 'https://openai.test/v1',
  OPENAI_MODEL: 'gpt-test',
  OPENAI_EXTRACTION_MODEL: 'gpt-test-vision',
  hasOpenAiKey: () => Boolean(settings.key),
}));

const CAPS = [
  { category: 'TRAVEL', label: 'Travel cap', cap: 25000, unit: 'per trip' },
  { category: 'LODGING', label: 'Lodging cap', cap: 4000, unit: 'per night' },
  { category: 'MEALS', label: 'Meals cap', cap: 1200, unit: 'per day' },
  { category: 'FUEL', label: 'Fuel cap', cap: 8000, unit: 'per month' },
  { category: 'OTHER', label: 'General claim cap', cap: 10000, unit: 'per claim' },
];

function file(name: string, type: string): LocalFile {
  return { name, type, size: 3, base64: 'AAEC', dataUrl: `data:${type};base64,AAEC` };
}

/** Stubs fetch with one canned OpenAI answer and records what was sent. */
function answer(status: number, body: unknown) {
  const calls: { url: string; init: RequestInit }[] = [];
  vi.stubGlobal(
    'fetch',
    vi.fn(async (url: string, init: RequestInit) => {
      calls.push({ url, init });
      return new Response(typeof body === 'string' ? body : JSON.stringify(body), { status });
    }),
  );
  return calls;
}

/** A Chat Completions response whose one tool call carries `args`. */
const toolCall = (args: unknown) => ({
  choices: [
    {
      message: {
        tool_calls: [
          {
            type: 'function',
            function: {
              name: 'record_receipt',
              arguments: typeof args === 'string' ? args : JSON.stringify(args),
            },
          },
        ],
      },
    },
  ],
});

const UNREADABLE = {
  severity: 'WARN',
  code: 'UNREADABLE',
  message:
    'The document could not be read confidently. Please check every field before submitting.',
  cap: null,
  observed: null,
};

const HEURISTIC_CONFIDENCE = { title: 0.2, category: 0.3, amount: 0, vendor: 0, dates: 0 };

beforeEach(() => {
  settings.key = 'sk-test';
});

afterEach(() => vi.restoreAllMocks());

describe('receipt extraction', () => {
  it('reads an image receipt into a proposal, checked against the caps', async () => {
    const calls = answer(
      200,
      toolCall({
        title: 'Hotel Sahyadri - 2 nights',
        category: 'lodging',
        amount: 'Rs 12,331.00',
        vendor: ' Hotel Sahyadri ',
        invoice_number: 'HS-9',
        invoice_date: '2026-09-03',
        travel_from: '2026-09-01',
        travel_to: '2026-09-03',
        justification: 'Stay for the Pune site audit.',
        line_items: [
          { description: 'Room', amount: '10,450' },
          { description: null, amount: 1881 },
        ],
        nights: 2,
        days: '3',
        confidence: { title: 0.9, category: 0.95, amount: 0.97, vendor: 0.9, dates: 0.8 },
        readable: true,
        notes: '',
      }),
    );

    const result = await extract([file('4f2a-hotel.jpg', 'image/jpeg')], CAPS, ['hotel.jpg']);

    expect(result).toEqual({
      title: 'Hotel Sahyadri - 2 nights',
      category: 'LODGING',
      amount: 12331,
      currency: 'INR',
      vendor: 'Hotel Sahyadri',
      invoiceNumber: 'HS-9',
      invoiceDate: '2026-09-03',
      travelDates: { from: '2026-09-01', to: '2026-09-03' },
      justification: 'Stay for the Pune site audit.',
      lineItems: [
        { description: 'Room', amount: 10450 },
        { description: 'None', amount: 1881 },
      ],
      confidence: { title: 0.9, category: 0.95, amount: 0.97, vendor: 0.9, dates: 0.8 },
      overallConfidence: 0.904,
      policyFindings: [
        {
          severity: 'BREACH',
          code: 'LODGING_CAP',
          // 6165.5 is an exact tie: Python rounds it to the even 6,166.
          message: 'Rs 6,166 per night over 2 night(s) exceeds the Rs 4,000 cap by Rs 4,331.',
          cap: 4000,
          observed: 6165.5,
        },
      ],
      notes: null,
      source: 'openai',
      model: 'gpt-test-vision',
      receiptIds: [],
    });

    // One forced function call, the receipt as an inline image.
    expect(calls).toHaveLength(1);
    expect(calls[0]!.url).toBe('https://openai.test/v1/chat/completions');
    expect((calls[0]!.init.headers as Record<string, string>).Authorization).toBe('Bearer sk-test');
    const sent = JSON.parse(String(calls[0]!.init.body));
    expect(sent.model).toBe('gpt-test-vision');
    expect(sent.max_completion_tokens).toBe(2048);
    expect(sent.tool_choice).toEqual({ type: 'function', function: { name: 'record_receipt' } });
    expect(sent.tools[0].function.name).toBe('record_receipt');
    expect(sent.tools[0].function.parameters.required).toContain('amount');
    expect(sent.messages[0].role).toBe('system');
    expect(sent.messages[0].content).toContain(
      '- Lodging cap: Rs 4,000 per night (category LODGING)\n',
    );
    expect(sent.messages[1].content).toEqual([
      { type: 'image_url', image_url: { url: 'data:image/jpeg;base64,AAEC' } },
      { type: 'text', text: 'Read the attached receipt and record the claim.' },
    ]);
  });

  it('sends a PDF as a file and several receipts as one claim', async () => {
    const calls = answer(200, toolCall({ category: 'TRAVEL', amount: 26000 }));
    const result = await extract(
      [file('ticket.pdf', 'application/pdf'), file('cab.png', 'image/png')],
      CAPS,
    );
    const parts = JSON.parse(String(calls[0]!.init.body)).messages[1].content;
    expect(parts[0]).toEqual({
      type: 'file',
      file: { filename: 'ticket.pdf', file_data: 'data:application/pdf;base64,AAEC' },
    });
    expect(parts[2].text).toMatch(/^Read the attached receipts and record the claim\. They belong/);
    expect(result.policyFindings).toEqual([
      {
        severity: 'BREACH',
        code: 'TRAVEL_CAP',
        message: 'Rs 26,000 exceeds the travel cap of Rs 25,000 per trip by Rs 1,000.',
        cap: 25000,
        observed: 26000,
      },
    ]);
  });

  it('shapes a junk payload into something the form can still show', async () => {
    answer(
      200,
      toolCall({
        title: '',
        category: 'hotel',
        amount: '₹ 9,500',
        nights: 'two',
        confidence: 'high',
        line_items: 'x',
        readable: 'no',
      }),
    );
    const result = await extract([file('bill.webp', 'image/webp')], CAPS);
    expect(result).toEqual({
      title: null,
      category: 'OTHER',
      amount: 9500,
      currency: 'INR',
      vendor: null,
      invoiceNumber: null,
      invoiceDate: null,
      travelDates: null,
      justification: null,
      lineItems: [],
      confidence: {},
      overallConfidence: 0,
      policyFindings: [
        {
          severity: 'INFO',
          code: 'OTHER_NEAR_CAP',
          message: 'Rs 9,500 is within 10% of the Rs 10,000 general claim cap.',
          cap: 10000,
          observed: 9500,
        },
      ],
      notes: null,
      source: 'openai',
      model: 'gpt-test-vision',
      receiptIds: [],
    });
  });

  it('falls back to the file name when the arguments are not JSON', async () => {
    answer(200, toolCall('{"amount": 12'));
    const result = await extract([file('x.jpg', 'image/jpeg')], CAPS, ['hotel-bill_taj.v2.jpg']);
    expect(result).toEqual({
      title: 'Hotel Bill Taj.V2',
      category: 'LODGING',
      amount: null,
      currency: 'INR',
      vendor: null,
      invoiceNumber: null,
      invoiceDate: null,
      travelDates: null,
      justification: null,
      lineItems: [],
      confidence: HEURISTIC_CONFIDENCE,
      overallConfidence: 0.1,
      policyFindings: [UNREADABLE],
      notes:
        'Automatic reading was unavailable, so only the file name could be used. ' +
        'Please fill in the amount and details.',
      source: 'heuristic',
      model: null,
      receiptIds: [],
    });
  });

  it('falls back when the model answers with prose instead of a call', async () => {
    answer(200, { choices: [{ message: { content: 'I think it is a hotel bill.' } }] });
    const result = await extract([file('meal.jpg', 'image/jpeg')], CAPS);
    expect(result.source).toBe('heuristic');
    expect(result.category).toBe('MEALS');
    expect(result.title).toBe('Meal');
  });

  it('says why when OpenAI refuses, and still proposes from the name', async () => {
    answer(429, { error: { message: 'You exceeded your quota', code: 'insufficient_quota' } });
    const result = await extract([file('fuel.png', 'image/png')], CAPS);
    expect(result.source).toBe('heuristic');
    expect(result.category).toBe('FUEL');
    expect(result.notes).toBe(
      'The OpenAI account has no credit left, so the model refused the request. ' +
        'Add credit under Billing; the key in backend/.env is fine. ' +
        'Please enter the details manually.',
    );

    answer(401, 'Unauthorized');
    expect((await extract([file('fuel.png', 'image/png')], CAPS)).notes).toBe(
      'The OpenAI API key was rejected. Check OPENAI_API_KEY in backend/.env. ' +
        'Please enter the details manually.',
    );
  });

  it('says so when OpenAI cannot be reached', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new TypeError('Failed to fetch');
      }),
    );
    const result = await extract([file('r.jpg', 'image/jpeg')], CAPS);
    expect(result.notes).toBe(
      "Could not reach OpenAI. Check the server's network. Please enter the details manually.",
    );
  });

  it('does not call the model for files it cannot read', async () => {
    const calls = answer(200, toolCall({ amount: 1 }));
    const result = await extract([file('notes.txt', 'text/plain')], CAPS);
    expect(calls).toHaveLength(0);
    expect(result.source).toBe('heuristic');
    expect(result.title).toBe('Notes');
  });

  it('without a key, proposes from the name and says why', async () => {
    settings.key = '';
    const calls = answer(200, toolCall({ amount: 1 }));
    const result = await extract([file('4f2a-uber_ride.pdf', 'application/pdf')], CAPS, [
      'uber_ride.pdf',
    ]);
    expect(calls).toHaveLength(0);
    expect(result).toEqual({
      title: 'Uber Ride',
      category: 'TRAVEL',
      amount: null,
      currency: 'INR',
      vendor: null,
      invoiceNumber: null,
      invoiceDate: null,
      travelDates: null,
      justification: null,
      lineItems: [],
      confidence: HEURISTIC_CONFIDENCE,
      overallConfidence: 0.1,
      policyFindings: [UNREADABLE],
      notes:
        'No OPENAI_API_KEY is configured, so the receipt was not read. ' +
        'Add a key to backend/.env to enable extraction.',
      source: 'heuristic',
      model: null,
      receiptIds: [],
    });
    expect(describeBackend()).toEqual({ configured: false, provider: 'openai', model: null });
  });

  it('reports the live backend when a key is set', () => {
    expect(describeBackend()).toEqual({
      configured: true,
      provider: 'openai',
      model: 'gpt-test-vision',
    });
  });

  it('rounds per-day meals and confidence exactly as Python does', async () => {
    answer(
      200,
      toolCall({ category: 'MEALS', amount: 3700, days: 3, confidence: { a: 0.0625, b: 0.0625 } }),
    );
    const result = await extract([file('m.jpg', 'image/jpeg')], CAPS);
    expect(result.overallConfidence).toBe(0.062);
    expect(result.policyFindings).toEqual([
      {
        severity: 'BREACH',
        code: 'MEALS_CAP',
        message: 'Rs 1,233 per day over 3 day(s) exceeds the Rs 1,200 cap by Rs 100.',
        cap: 1200,
        observed: 3700 / 3,
      },
    ]);
  });
});

describe('the sample extraction', () => {
  it('has the shape the backend returns', () => {
    expect(sampleExtraction(CAPS)).toEqual({
      title: 'Taj Vivanta, Pune - 2 nights',
      category: 'LODGING',
      amount: 11800,
      currency: 'INR',
      vendor: 'Taj Vivanta Pune',
      invoiceNumber: 'TV-2026-44817',
      invoiceDate: '2026-09-04',
      travelDates: { from: '2026-09-02', to: '2026-09-04' },
      justification:
        'Two-night stay in Pune for the on-site client visit with the procurement team.',
      lineItems: [
        { description: 'Room charges (2 nights)', amount: 10000 },
        { description: 'GST @ 18%', amount: 1800 },
      ],
      confidence: { title: 0.94, category: 0.98, amount: 0.99, vendor: 0.97, dates: 0.92 },
      overallConfidence: 0.96,
      policyFindings: [
        {
          severity: 'BREACH',
          code: 'LODGING_CAP',
          message: 'Rs 5,900 per night over 2 night(s) exceeds the Rs 4,000 cap by Rs 3,800.',
          cap: 4000,
          observed: 5900,
        },
      ],
      notes: 'Room rate is Rs 5,000 per night before tax.',
      source: 'sample',
      model: null,
      receiptIds: [],
    });
  });

  it('carries no findings when there are no caps', () => {
    expect(sampleExtraction([]).policyFindings).toEqual([]);
  });
});
