/**
 * Invite landing page.
 *
 * Reached from a shared `/chat/join/<code>` link. The invite is validated
 * against the same rules the room settings dialog enforces, so a revoked,
 * expired or exhausted link explains itself rather than failing silently.
 */

import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { AlertTriangle, Clock, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { GroupAvatar, UserAvatar } from '@/components/chat/UserAvatar';
import { useChat } from '@/lib/chat-store';
import { formatUntil } from '@/lib/time';

export const JoinRoom: React.FC = () => {
  const { code = '' } = useParams<{ code: string }>();
  const navigate = useNavigate();
  const { roomByCode, joinByCode, userById, currentUser, inviteStatus, roomTitle } = useChat();
  const [error, setError] = useState<string | null>(null);

  const room = roomByCode(code);
  const status = inviteStatus(room?.invite);
  const alreadyMember = room?.participantIds.includes(currentUser.id) ?? false;
  const usable = Boolean(room) && (status === 'active' || alreadyMember);

  return (
    <div className="flex min-h-[70vh] items-center justify-center px-4">
      <div className="panel-lift w-full max-w-md p-8 text-center">
        {room && usable ? (
          <>
            <p className="label-eyebrow">You have been invited to</p>
            <div className="mt-5 flex flex-col items-center gap-3">
              <GroupAvatar name={roomTitle(room)} color={room.color} photo={room.photo} size={64} />
              <h1 className="text-xl font-semibold text-ink">{roomTitle(room)}</h1>
              {room.description && <p className="text-xs text-muted">{room.description}</p>}
              <div className="flex -space-x-2">
                {room.participantIds.slice(0, 6).map((id) => (
                  <UserAvatar key={id} user={userById(id)} size={28} />
                ))}
              </div>
              <p className="flex items-center gap-1.5 text-xs text-muted">
                <Users className="h-3.5 w-3.5" /> {room.participantIds.length} members
              </p>
              {room.invite?.expiresAt && !alreadyMember && (
                <p className="flex items-center gap-1.5 font-mono text-[12px] text-muted">
                  <Clock className="h-3 w-3" /> Expires {formatUntil(room.invite.expiresAt)}
                  {room.invite.maxUses
                    ? ` · ${room.invite.maxUses - room.invite.uses} uses left`
                    : ''}
                </p>
              )}
            </div>

            {error && <p className="mt-4 text-xs text-strand-red">{error}</p>}

            <Button
              className="mt-6 w-full rounded-md"
              onClick={() => {
                const result = joinByCode(code);
                if (result.error) {
                  setError(result.error);
                  return;
                }
                navigate('/chat');
              }}
            >
              {alreadyMember ? 'Open conversation' : 'Join group'}
            </Button>
          </>
        ) : (
          <>
            <span className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-strand-red/10 text-strand-red">
              <AlertTriangle className="h-4.5 w-4.5" />
            </span>
            <h1 className="mt-4 text-lg font-semibold text-ink">
              {status === 'expired'
                ? 'This invite has expired'
                : status === 'exhausted'
                  ? 'This invite is fully used'
                  : 'This invite is no longer valid'}
            </h1>
            <p className="mt-2 text-[13px] leading-relaxed text-muted">
              {status === 'expired'
                ? 'Ask a group admin to generate a fresh link.'
                : status === 'exhausted'
                  ? 'It reached its usage limit. Ask an admin for a new one.'
                  : 'It was revoked or regenerated by the group admin.'}
            </p>
            <Button
              variant="secondary"
              className="mt-6 w-full rounded-md"
              onClick={() => navigate('/chat')}
            >
              Back to conversations
            </Button>
          </>
        )}
      </div>
    </div>
  );
};

export default JoinRoom;
